[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings =["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true  
# if it is true, we are allowing foundry to execute commands directly on the machine

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
